from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from dateutil.parser import isoparse
from typing import cast
from uuid import UUID
import datetime

if TYPE_CHECKING:
  from ..models.policy import Policy
  from ..models.policy_version_created_by import PolicyVersionCreatedBy





T = TypeVar("T", bound="PolicyVersion")



@_attrs_define
class PolicyVersion:
    """ Policy version serializer for public API.

    Exposes auto-generated structure IDs (category/rule/sub-rule IDs) in responses
    so users can reference specific rules. IDs are immutable - any IDs provided in
    create/update requests are ignored and regenerated by the backend.

        Attributes:
            id (UUID):
            version_name (str):
            content (Any):
            created_at (datetime.datetime):
            updated_at (datetime.datetime):
            policy (Policy): Policy serializer
            created_by (PolicyVersionCreatedBy): Minimal user serializer for audit metadata on policy versions.
            base_version_id (None | UUID):
     """

    id: UUID
    version_name: str
    content: Any
    created_at: datetime.datetime
    updated_at: datetime.datetime
    policy: Policy
    created_by: PolicyVersionCreatedBy
    base_version_id: None | UUID
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.policy import Policy
        from ..models.policy_version_created_by import PolicyVersionCreatedBy
        id = str(self.id)

        version_name = self.version_name

        content = self.content

        created_at = self.created_at.isoformat()

        updated_at = self.updated_at.isoformat()

        policy = self.policy.to_dict()

        created_by = self.created_by.to_dict()

        base_version_id: None | str
        if isinstance(self.base_version_id, UUID):
            base_version_id = str(self.base_version_id)
        else:
            base_version_id = self.base_version_id


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "id": id,
            "version_name": version_name,
            "content": content,
            "created_at": created_at,
            "updated_at": updated_at,
            "policy": policy,
            "created_by": created_by,
            "base_version_id": base_version_id,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.policy import Policy
        from ..models.policy_version_created_by import PolicyVersionCreatedBy
        d = dict(src_dict)
        id = UUID(d.pop("id"))




        version_name = d.pop("version_name")

        content = d.pop("content")

        created_at = isoparse(d.pop("created_at"))




        updated_at = isoparse(d.pop("updated_at"))




        policy = Policy.from_dict(d.pop("policy"))




        created_by = PolicyVersionCreatedBy.from_dict(d.pop("created_by"))




        def _parse_base_version_id(data: object) -> None | UUID:
            if data is None:
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                base_version_id_type_0 = UUID(data)



                return base_version_id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | UUID, data)

        base_version_id = _parse_base_version_id(d.pop("base_version_id"))


        policy_version = cls(
            id=id,
            version_name=version_name,
            content=content,
            created_at=created_at,
            updated_at=updated_at,
            policy=policy,
            created_by=created_by,
            base_version_id=base_version_id,
        )


        policy_version.additional_properties = d
        return policy_version

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
