from __future__ import annotations

from collections import defaultdict
from pathlib import Path
import re
from typing import Any

from ruamel.yaml import YAML


ROOT_DIR = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT_DIR / "openapi" / "wrappers.yml"
README_BLOCKS_PATH = ROOT_DIR / "openapi" / "readme_blocks.yml"
README_PATH = ROOT_DIR / "README.md"
API_DIR = ROOT_DIR / "src" / "roe" / "api"
REGISTRY_PATH = API_DIR / "_generated_registry.py"
README_BLOCK_START = "<!-- ROE-SDK:GENERATED-FRIENDLY-APIS:START -->"
README_BLOCK_END = "<!-- ROE-SDK:GENERATED-FRIENDLY-APIS:END -->"

HEADER = (
    '"""Auto-generated friendly API facades for the Roe SDK."""\n'
    "\n"
    "# Generated by scripts/generate-sdk from openapi/wrappers.yml.\n"
    "# Do not edit by hand.\n"
    "\n"
    "from __future__ import annotations\n"
    "\n"
)


def _load_contract() -> dict[str, Any]:
    yaml = YAML(typ="safe")
    data = yaml.load(CONTRACT_PATH.read_text())
    if not isinstance(data, dict) or not isinstance(data.get("apis"), dict):
        raise ValueError(f"{CONTRACT_PATH} must contain an 'apis' mapping")
    return data


def _load_readme_block() -> str:
    yaml = YAML(typ="safe")
    data = yaml.load(README_BLOCKS_PATH.read_text(encoding="utf-8"))
    try:
        block = data["blocks"]["generated_friendly_apis"]["python"]
    except (KeyError, TypeError) as exc:
        raise ValueError(
            f"{README_BLOCKS_PATH} must contain blocks.generated_friendly_apis.python"
        ) from exc
    if not isinstance(block, str) or not block.strip():
        raise ValueError(
            f"{README_BLOCKS_PATH} blocks.generated_friendly_apis.python must be a non-empty string"
        )
    return block.strip()


def _sync_readme_block() -> None:
    block = _load_readme_block()
    readme = README_PATH.read_text(encoding="utf-8")
    replacement = f"{README_BLOCK_START}\n{block}\n{README_BLOCK_END}"
    pattern = re.compile(
        rf"{re.escape(README_BLOCK_START)}.*?{re.escape(README_BLOCK_END)}",
        re.DOTALL,
    )
    updated, count = pattern.subn(replacement, readme, count=1)
    if count != 1:
        raise ValueError(
            f"{README_PATH} must contain {README_BLOCK_START} and {README_BLOCK_END}"
        )
    README_PATH.write_text(updated, encoding="utf-8")


def _module_import_parts(module_path: str) -> tuple[str, str]:
    package, module_name = module_path.rsplit(".", 1)
    return package, module_name


def _class_import_parts(import_path: str) -> tuple[str, str]:
    module, class_name = import_path.rsplit(".", 1)
    return module, class_name


def _default_expr(value: Any) -> str:
    if value is None:
        return "None"
    return repr(value)


def _simple_method(operation: dict[str, Any]) -> str:
    method_name = operation["method_name"]
    endpoint_name = _module_import_parts(operation["endpoint_module"])[1]
    return_type = operation["return_type"]
    docstring = operation.get("docstring", "")
    empty_message = operation["empty_response_message"]
    params = operation.get("parameters") or []

    signature_parts = ["self"]
    for param in params:
        signature_parts.append(
            f"{param['name']}: {param['annotation']} = {_default_expr(param.get('default'))}"
        )
    if len(signature_parts) == 1:
        signature = "self"
        signature_prefix = f"    def {method_name}({signature}) -> {return_type}:\n"
    else:
        formatted_signature = ",\n".join(f"        {part}" for part in signature_parts)
        signature_prefix = (
            f"    def {method_name}(\n{formatted_signature},\n    ) -> {return_type}:\n"
        )

    call_args = ["client=self._raw"]
    for param in params:
        name = param["name"]
        if param.get("pass_unset_when_none"):
            call_args.append(f"{name}={name} if {name} is not None else UNSET")
        else:
            call_args.append(f"{name}={name}")

    call_args_block = ",\n".join(f"            {arg}" for arg in call_args)

    return (
        signature_prefix + f'        """{docstring}"""\n'
        f"        response = {endpoint_name}.sync_detailed(\n"
        f"{call_args_block},\n"
        f"        )\n"
        "        translate_response(response)\n"
        "        if response.parsed is None:\n"
        f'            raise RoeAPIException("{empty_message}")\n'
        "        return response.parsed\n"
    )


def _table_upload_method(operation: dict[str, Any]) -> str:
    endpoint_name = _module_import_parts(operation["endpoint_module"])[1]
    method_name = operation["method_name"]
    return_type = operation["return_type"]
    body_type = operation["body_type"]
    docstring = operation.get("docstring", "")
    empty_message = operation["empty_response_message"]

    return f'''    def {method_name}(
        self,
        *,
        table_name: str,
        file: str | Path | bytes | BinaryIO | FileUpload,
        with_headers: bool = True,
        organization_id: str | UUID | None = None,
        filename: str | None = None,
        mime_type: str | None = None,
    ) -> {return_type}:
        """{docstring}

        Args:
            table_name: Name of the table to create.
            file: CSV file path, bytes, binary file object, or ``FileUpload``.
            with_headers: Whether the first CSV row contains column headers.
            organization_id: Optional override; defaults to the client's configured org.
            filename: Filename to use for bytes/file objects.
            mime_type: MIME type override. Defaults to ``text/csv`` for ``.csv`` names.
        """
        resolved_org: UUID | Unset
        candidate = organization_id or self.config.organization_id
        resolved_org = UUID(str(candidate)) if candidate else UNSET

        upload_file, close_after = self._as_generated_file(file, filename, mime_type)
        try:
            body = {body_type}(
                table_name=table_name,
                file=upload_file,
                with_headers=with_headers,
                organization_id=resolved_org,
            )
            response = {endpoint_name}.sync_detailed(client=self._raw, body=body)
            translate_response(response)
            if not isinstance(response.parsed, {return_type}):
                raise RoeAPIException("{empty_message}")
            return response.parsed
        finally:
            if close_after:
                upload_file.payload.close()

    @staticmethod
    def _as_generated_file(
        file: str | Path | bytes | BinaryIO | FileUpload,
        filename: str | None,
        mime_type: str | None,
    ) -> tuple[File, bool]:
        if isinstance(file, FileUpload):
            payload = file.open()
            effective_filename = filename or file.effective_filename
            effective_mime_type = mime_type or file.effective_mime_type
            return (
                File(
                    payload=payload,
                    file_name=effective_filename,
                    mime_type=effective_mime_type,
                ),
                file.path is not None,
            )

        if isinstance(file, (str, Path)):
            path = Path(file)
            payload = path.open("rb")
            effective_filename = filename or path.name
            return (
                File(
                    payload=payload,
                    file_name=effective_filename,
                    mime_type=_mime_type(effective_filename, mime_type),
                ),
                True,
            )

        if isinstance(file, bytes):
            effective_filename = filename or "upload.csv"
            return (
                File(
                    payload=BytesIO(file),
                    file_name=effective_filename,
                    mime_type=_mime_type(effective_filename, mime_type),
                ),
                True,
            )

        effective_filename = filename or Path(getattr(file, "name", "upload.csv")).name
        return (
            File(
                payload=file,
                file_name=effective_filename,
                mime_type=_mime_type(effective_filename, mime_type),
            ),
            False,
        )
'''


def _render_api_module(api_name: str, spec: dict[str, Any]) -> str:
    class_name = spec["class_name"]
    operations = spec.get("operations") or []

    endpoint_imports: dict[str, list[str]] = defaultdict(list)
    model_imports: dict[str, list[str]] = defaultdict(list)
    needs_unset = False
    needs_roe_api_exception = False
    needs_table_upload_helpers = False

    methods: list[str] = []
    for operation in operations:
        package, endpoint_name = _module_import_parts(operation["endpoint_module"])
        endpoint_imports[package].append(endpoint_name)

        return_module, return_class = _class_import_parts(operation["return_import"])
        model_imports[return_module].append(return_class)

        kind = operation.get("kind", "simple")
        if kind == "simple":
            needs_roe_api_exception = True
            if any(
                param.get("pass_unset_when_none")
                for param in operation.get("parameters") or []
            ):
                needs_unset = True
            methods.append(_simple_method(operation))
        elif kind == "table_upload":
            needs_roe_api_exception = True
            needs_table_upload_helpers = True
            needs_unset = True
            body_module, body_class = _class_import_parts(operation["body_import"])
            model_imports[body_module].append(body_class)
            methods.append(_table_upload_method(operation))
        else:
            raise ValueError(f"Unsupported wrapper kind {kind!r} in {api_name}")

    lines = [HEADER]
    if needs_table_upload_helpers:
        lines.append("from io import BytesIO\n")
        lines.append("import mimetypes\n")
        lines.append("from pathlib import Path\n")
        lines.append("from typing import BinaryIO\n")
        lines.append("from uuid import UUID\n")
        lines.append("\n")

    for package, names in sorted(endpoint_imports.items()):
        unique_names = sorted(set(names))
        if len(unique_names) == 1:
            lines.append(f"from {package} import {unique_names[0]}\n")
        else:
            lines.append(f"from {package} import (\n")
            for name in unique_names:
                lines.append(f"    {name},\n")
            lines.append(")\n")
    lines.append("from roe._generated.client import AuthenticatedClient\n")
    for module, names in sorted(model_imports.items()):
        joined = ", ".join(sorted(set(names)))
        lines.append(f"from {module} import {joined}\n")
    if needs_table_upload_helpers:
        lines.append("from roe._generated.types import File, UNSET, Unset\n")
    elif needs_unset:
        lines.append("from roe._generated.types import UNSET\n")
    lines.append("from roe.config import RoeConfig\n")
    if needs_roe_api_exception:
        lines.append("from roe.exceptions import RoeAPIException, translate_response\n")
    else:
        lines.append("from roe.exceptions import translate_response\n")
    if needs_table_upload_helpers:
        lines.append("from roe.models import FileUpload\n")

    lines.append("\n\n")
    lines.append(f"class {class_name}:\n")
    lines.append(f'    """{spec.get("docstring", "")}"""\n')
    lines.append("\n")
    lines.append(
        "    def __init__(self, config: RoeConfig, raw_client: AuthenticatedClient):\n"
    )
    lines.append("        self.config = config\n")
    lines.append("        self._raw = raw_client\n")
    lines.append("\n")
    lines.append("\n".join(methods))

    if needs_table_upload_helpers:
        lines.append(
            "\n\ndef _mime_type(filename: str, override: str | None) -> str:\n"
            "    if override:\n"
            "        return override\n"
            "    guessed, _ = mimetypes.guess_type(filename)\n"
            '    return guessed or "text/csv"\n'
        )

    content = "".join(lines)
    return content.rstrip() + "\n"


def _render_registry(apis: dict[str, dict[str, Any]]) -> str:
    lines = [
        '"""Auto-generated friendly API registry for the Roe SDK."""\n',
        "\n",
        "# Generated by scripts/generate-sdk from openapi/wrappers.yml.\n",
        "# Do not edit by hand.\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
    ]
    for api_name, spec in sorted(apis.items()):
        lines.append(f"from roe.api.{api_name} import {spec['class_name']}\n")
    lines.append("\n\n")
    lines.append("GENERATED_API_CLASSES = {\n")
    for api_name, spec in sorted(apis.items()):
        lines.append(f'    "{api_name}": {spec["class_name"]},\n')
    lines.append("}\n")
    return "".join(lines)


def main() -> None:
    contract = _load_contract()
    apis = contract["apis"]
    API_DIR.mkdir(parents=True, exist_ok=True)

    for api_name, spec in sorted(apis.items()):
        target = API_DIR / f"{api_name}.py"
        target.write_text(_render_api_module(api_name, spec))

    REGISTRY_PATH.write_text(_render_registry(apis))
    _sync_readme_block()
    print(
        f"Generated {len(apis)} friendly API wrapper modules from "
        f"{CONTRACT_PATH.relative_to(ROOT_DIR)}"
    )


if __name__ == "__main__":
    main()
