from __future__ import annotations

from collections import defaultdict
from pathlib import Path
import re
from typing import Any

from ruamel.yaml import YAML

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 codegen envs
    import tomli as tomllib


ROOT_DIR = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT_DIR / "openapi" / "wrappers.yml"
README_BLOCKS_PATH = ROOT_DIR / "openapi" / "readme_blocks.yml"
README_PATH = ROOT_DIR / "README.md"
API_DIR = ROOT_DIR / "src" / "roe" / "api"
REGISTRY_PATH = API_DIR / "_generated_registry.py"
README_BANNER_START = "<!-- ROE-SDK:RELEASE-BANNER:START -->"
README_BANNER_END = "<!-- ROE-SDK:RELEASE-BANNER:END -->"
README_BLOCK_START = "<!-- ROE-SDK:GENERATED-FRIENDLY-APIS:START -->"
README_BLOCK_END = "<!-- ROE-SDK:GENERATED-FRIENDLY-APIS:END -->"

# Suffix appended to contract class names when emitting base-class modules
# (split mode) for APIs that also contain hand-written ``manual`` operations.
GENERATED_CLASS_SUFFIX = "Generated"

_ANY_RE = re.compile(r"\bAny\b")

HEADER = (
    '"""Auto-generated friendly API facades for the Roe SDK."""\n'
    "\n"
    "# Generated by scripts/generate-sdk from openapi/wrappers.yml.\n"
    "# Do not edit by hand.\n"
    "\n"
    "from __future__ import annotations\n"
    "\n"
)

BASE_HEADER = (
    '"""Auto-generated base classes for hand-written Roe SDK API facades."""\n'
    "\n"
    "# Generated by scripts/generate-sdk from openapi/wrappers.yml.\n"
    "# Do not edit by hand.\n"
    "\n"
    "from __future__ import annotations\n"
    "\n"
)


class ManualWrapperParityError(ValueError):
    """Raised when a ``manual`` operation has no matching hand-written method."""


def _load_contract() -> dict[str, Any]:
    yaml = YAML(typ="safe")
    data = yaml.load(CONTRACT_PATH.read_text())
    if not isinstance(data, dict) or not isinstance(data.get("apis"), dict):
        raise ValueError(f"{CONTRACT_PATH} must contain an 'apis' mapping")
    return data


def _load_readme_block() -> str:
    yaml = YAML(typ="safe")
    data = yaml.load(README_BLOCKS_PATH.read_text(encoding="utf-8"))
    try:
        block = data["blocks"]["generated_friendly_apis"]["python"]
    except (KeyError, TypeError) as exc:
        raise ValueError(
            f"{README_BLOCKS_PATH} must contain blocks.generated_friendly_apis.python"
        ) from exc
    if not isinstance(block, str) or not block.strip():
        raise ValueError(
            f"{README_BLOCKS_PATH} blocks.generated_friendly_apis.python must be a non-empty string"
        )
    return block.strip()


def _replace_marked_block(
    readme: str,
    *,
    start_marker: str,
    end_marker: str,
    replacement: str,
) -> str:
    block = f"{start_marker}\n{replacement.strip()}\n{end_marker}"
    pattern = re.compile(
        rf"{re.escape(start_marker)}.*?{re.escape(end_marker)}",
        re.DOTALL,
    )
    updated, count = pattern.subn(block, readme, count=1)
    if count != 1:
        raise ValueError(
            f"{README_PATH} must contain {start_marker} and {end_marker}"
        )
    return updated


def _load_project_version() -> str:
    data = tomllib.loads((ROOT_DIR / "pyproject.toml").read_text(encoding="utf-8"))
    version = data.get("project", {}).get("version")
    if not isinstance(version, str) or not version:
        raise ValueError("pyproject.toml must contain project.version")
    return version


def _load_release_marker() -> str:
    marker = (ROOT_DIR / ".roe-main-release-version").read_text(encoding="utf-8").strip()
    if not marker:
        raise ValueError(".roe-main-release-version must not be empty")
    return marker


def _render_release_banner() -> str:
    version = _load_project_version()
    marker = _load_release_marker()
    return (
        f"> **v{version}** - Schema synchronization across the public SDKs: roe-ai\n"
        f"> (Python), roe-typescript, and roe-golang. This release is generated from\n"
        f"> SDK OpenAPI marker `{marker}`, and all public package metadata is bumped to\n"
        f"> {version}.\n"
        "> Python friendly wrappers are generated from `openapi/wrappers.yml`;\n"
        "> current generated facades include `client.discovery` and `client.tables`."
    )


def _sync_readme_release_banner() -> None:
    readme = README_PATH.read_text(encoding="utf-8")
    updated = _replace_marked_block(
        readme,
        start_marker=README_BANNER_START,
        end_marker=README_BANNER_END,
        replacement=_render_release_banner(),
    )
    README_PATH.write_text(updated, encoding="utf-8")


def _sync_readme_block() -> None:
    block = _load_readme_block()
    readme = README_PATH.read_text(encoding="utf-8")
    updated = _replace_marked_block(
        readme,
        start_marker=README_BLOCK_START,
        end_marker=README_BLOCK_END,
        replacement=block,
    )
    README_PATH.write_text(updated, encoding="utf-8")


def _module_import_parts(module_path: str) -> tuple[str, str]:
    package, module_name = module_path.rsplit(".", 1)
    return package, module_name


def _class_import_parts(import_path: str) -> tuple[str, str]:
    module, class_name = import_path.rsplit(".", 1)
    return module, class_name


def _default_expr(value: Any) -> str:
    if value is None:
        return "None"
    return repr(value)


def _docstring_block(docstring: str, indent: str) -> str:
    """Render a (possibly multi-line) docstring at the given indentation."""
    lines = docstring.splitlines() or [""]
    if len(lines) == 1:
        return f'{indent}"""{lines[0]}"""\n'
    rendered = [f'{indent}"""{lines[0]}\n']
    for line in lines[1:]:
        rendered.append(f"{indent}{line}\n" if line else "\n")
    rendered.append(f'{indent}"""\n')
    return "".join(rendered)


def _operations(spec: dict[str, Any]) -> list[dict[str, Any]]:
    return spec.get("operations") or []


def _namespaces(spec: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return spec.get("namespaces") or {}


def _body_kind_ops(spec: dict[str, Any]) -> list[dict[str, Any]]:
    return [op for op in _operations(spec) if op.get("kind") == "body"]


def _spec_has_manual(spec: dict[str, Any]) -> bool:
    if any(op.get("kind") == "manual" for op in _operations(spec)):
        return True
    return any(
        op.get("kind") == "manual"
        for ns_spec in _namespaces(spec).values()
        for op in _operations(ns_spec)
    )


def _has_generated_ops(spec: dict[str, Any]) -> bool:
    if any(op.get("kind") != "manual" for op in _operations(spec)):
        return True
    return any(
        op.get("kind") != "manual"
        for ns_spec in _namespaces(spec).values()
        for op in _operations(ns_spec)
    )


def _collect_manual_method_names(spec: dict[str, Any]) -> list[str]:
    names = [
        op["method_name"] for op in _operations(spec) if op.get("kind") == "manual"
    ]
    for ns_spec in _namespaces(spec).values():
        names.extend(
            op["method_name"]
            for op in _operations(ns_spec)
            if op.get("kind") == "manual"
        )
    return names


def _check_manual_parity(apis: dict[str, dict[str, Any]], api_dir: Path) -> None:
    """Assert every ``manual`` operation exists in the hand-written facade.

    Manual operations are never generated; the hand-written module
    ``src/roe/api/{api}.py`` must define each one. Collects every missing
    method across all APIs and fails loudly with the full list.
    """
    problems: list[str] = []
    for api_name, spec in sorted(apis.items()):
        manual_names = _collect_manual_method_names(spec)
        if not manual_names:
            continue
        facade = api_dir / f"{api_name}.py"
        if not facade.exists():
            problems.append(
                f"{api_name}: hand-written facade {facade} is missing "
                f"(manual operations: {', '.join(manual_names)})"
            )
            continue
        text = facade.read_text(encoding="utf-8")
        for name in manual_names:
            if f"def {name}(" not in text:
                problems.append(
                    f"{api_name}: manual operation {name!r} not found "
                    f"(expected `def {name}(` in {facade})"
                )
    if problems:
        raise ManualWrapperParityError(
            "Manual wrapper parity check failed:\n"
            + "\n".join(f"  - {problem}" for problem in problems)
        )


def _simple_method(operation: dict[str, Any]) -> str:
    method_name = operation["method_name"]
    endpoint_name = _module_import_parts(operation["endpoint_module"])[1]
    return_type = operation["return_type"]
    docstring = operation.get("docstring", "")
    empty_message = operation["empty_response_message"]
    params = operation.get("parameters") or []

    signature_parts = ["self"]
    for param in params:
        signature_parts.append(
            f"{param['name']}: {param['annotation']} = {_default_expr(param.get('default'))}"
        )
    if len(signature_parts) == 1:
        signature = "self"
        signature_prefix = f"    def {method_name}({signature}) -> {return_type}:\n"
    else:
        formatted_signature = ",\n".join(f"        {part}" for part in signature_parts)
        signature_prefix = (
            f"    def {method_name}(\n{formatted_signature},\n    ) -> {return_type}:\n"
        )

    call_args = ["client=self._raw"]
    for param in params:
        name = param["name"]
        if param.get("pass_unset_when_none"):
            call_args.append(f"{name}={name} if {name} is not None else UNSET")
        else:
            call_args.append(f"{name}={name}")

    call_args_block = ",\n".join(f"            {arg}" for arg in call_args)

    return (
        signature_prefix + f'        """{docstring}"""\n'
        f"        response = {endpoint_name}.sync_detailed(\n"
        f"{call_args_block},\n"
        f"        )\n"
        "        translate_response(response)\n"
        "        if response.parsed is None:\n"
        f'            raise RoeAPIException("{empty_message}")\n'
        "        return response.parsed\n"
    )


def _table_upload_method(operation: dict[str, Any]) -> str:
    endpoint_name = _module_import_parts(operation["endpoint_module"])[1]
    method_name = operation["method_name"]
    return_type = operation["return_type"]
    body_type = operation["body_type"]
    docstring = operation.get("docstring", "")
    empty_message = operation["empty_response_message"]

    return f'''    def {method_name}(
        self,
        *,
        table_name: str,
        file: str | Path | bytes | BinaryIO | FileUpload,
        with_headers: bool = True,
        organization_id: str | UUID | None = None,
        filename: str | None = None,
        mime_type: str | None = None,
    ) -> {return_type}:
        """{docstring}

        Args:
            table_name: Name of the table to create.
            file: CSV file path, bytes, binary file object, or ``FileUpload``.
            with_headers: Whether the first CSV row contains column headers.
            organization_id: Optional override; defaults to the client's configured org.
            filename: Filename to use for bytes/file objects.
            mime_type: MIME type override. Defaults to ``text/csv`` for ``.csv`` names.
        """
        resolved_org: UUID | Unset
        candidate = organization_id or self.config.organization_id
        resolved_org = UUID(str(candidate)) if candidate else UNSET

        upload_file, close_after = self._as_generated_file(file, filename, mime_type)
        try:
            body = {body_type}(
                table_name=table_name,
                file=upload_file,
                with_headers=with_headers,
                organization_id=resolved_org,
            )
            response = {endpoint_name}.sync_detailed(client=self._raw, body=body)
            translate_response(response)
            if not isinstance(response.parsed, {return_type}):
                raise RoeAPIException("{empty_message}")
            return response.parsed
        finally:
            if close_after:
                upload_file.payload.close()

    @staticmethod
    def _as_generated_file(
        file: str | Path | bytes | BinaryIO | FileUpload,
        filename: str | None,
        mime_type: str | None,
    ) -> tuple[File, bool]:
        if isinstance(file, FileUpload):
            payload = file.open()
            effective_filename = filename or file.effective_filename
            effective_mime_type = mime_type or file.effective_mime_type
            return (
                File(
                    payload=payload,
                    file_name=effective_filename,
                    mime_type=effective_mime_type,
                ),
                file.path is not None,
            )

        if isinstance(file, (str, Path)):
            path = Path(file)
            payload = path.open("rb")
            effective_filename = filename or path.name
            return (
                File(
                    payload=payload,
                    file_name=effective_filename,
                    mime_type=_mime_type(effective_filename, mime_type),
                ),
                True,
            )

        if isinstance(file, bytes):
            effective_filename = filename or "upload.csv"
            return (
                File(
                    payload=BytesIO(file),
                    file_name=effective_filename,
                    mime_type=_mime_type(effective_filename, mime_type),
                ),
                True,
            )

        effective_filename = filename or Path(getattr(file, "name", "upload.csv")).name
        return (
            File(
                payload=file,
                file_name=effective_filename,
                mime_type=_mime_type(effective_filename, mime_type),
            ),
            False,
        )
'''


def _body_kind_method(operation: dict[str, Any]) -> str:
    """Render a ``kind: body`` operation as a facade method.

    Conventions mirror the hand-written facades (agents.py / policies.py):

    - no ``body_type``: ``request_raw(self._raw, endpoint, *path_args,
      **query, organization_id=self._org_id)``; ``ReturnType.from_dict``
      for object returns, a guarded list comprehension for
      ``return_shape: list``, implicit ``None`` when no ``return_type``.
    - with ``body_type``: build the request model from body-location
      parameters and dispatch through ``request_json`` (forced-JSON body),
      returning ``resp.parsed`` (or nothing when no ``return_type``).
    - ``refetch_with_retrieve``: POST via ``request_raw`` with the body,
      extract the created ``id`` and return ``self.retrieve(...)``.
    """
    method_name = operation["method_name"]
    endpoint_name = _module_import_parts(operation["endpoint_module"])[1]
    params = operation.get("parameters") or []
    docstring = operation.get("docstring") or ""
    return_type = operation.get("return_type")
    return_shape = operation.get("return_shape", "object")
    body_type = operation.get("body_type")
    refetch = bool(operation.get("refetch_with_retrieve"))
    empty_message = operation.get("empty_response_message")

    path_params = [p for p in params if p.get("location") == "path"]
    query_params = [p for p in params if p.get("location") == "query"]
    body_params = [p for p in params if p.get("location") == "body"]

    if return_shape not in ("object", "list"):
        raise ValueError(
            f"Unsupported return_shape {return_shape!r} in operation {method_name!r}"
        )
    if return_shape == "list":
        if return_type is None or body_type is not None:
            raise ValueError(
                f"return_shape: list requires a return_type and no body_type "
                f"(operation {method_name!r})"
            )
        return_annotation = f"list[{return_type}]"
    elif return_type is not None:
        return_annotation = return_type
    else:
        return_annotation = "None"
    if refetch and (body_type is None or return_type is None):
        raise ValueError(
            f"refetch_with_retrieve requires body_type and return_type "
            f"(operation {method_name!r})"
        )

    signature_parts = ["self"]
    for param in params:
        part = f"{param['name']}: {param['annotation']}"
        if "default" in param:
            part = f"{part} = {_default_expr(param['default'])}"
        signature_parts.append(part)
    if len(signature_parts) == 1:
        lines = [f"    def {method_name}(self) -> {return_annotation}:\n"]
    else:
        formatted_signature = ",\n".join(f"        {part}" for part in signature_parts)
        lines = [
            f"    def {method_name}(\n{formatted_signature},\n"
            f"    ) -> {return_annotation}:\n"
        ]
    if docstring:
        lines.append(_docstring_block(docstring, "        "))

    def _path_expr(param: dict[str, Any]) -> str:
        if param.get("coerce") == "uuid":
            return f"UUID(str({param['name']}))"
        return param["name"]

    call_args = ["self._raw", endpoint_name]
    call_args.extend(_path_expr(param) for param in path_params)
    if body_type:
        call_args.append("body=body")
    for param in query_params:
        wire = param.get("wire_name", param["name"])
        name = param["name"]
        if param.get("pass_unset_when_none"):
            call_args.append(f"{wire}={name} if {name} is not None else UNSET")
        else:
            call_args.append(f"{wire}={name}")
    call_args.append("organization_id=self._org_id")

    def _request_call(prefix: str, func: str) -> str:
        joined = ",\n".join(f"            {arg}" for arg in call_args)
        return f"        {prefix}{func}(\n{joined},\n        )\n"

    if body_type:
        body_args: list[str] = []
        for param in body_params:
            wire = param.get("wire_name", param["name"])
            name = param["name"]
            or_empty = param.get("or_empty")
            if or_empty == "list":
                body_args.append(f"{wire}={name} or []")
            elif or_empty == "dict":
                body_args.append(f"{wire}={name} or {{}}")
            elif or_empty is not None:
                raise ValueError(
                    f"Unsupported or_empty {or_empty!r} in operation {method_name!r}"
                )
            elif param.get("pass_unset_when_none"):
                body_args.append(f"{wire}={name} if {name} is not None else UNSET")
            else:
                body_args.append(f"{wire}={name}")
        if operation.get("inject_organization_id"):
            required_count = sum(1 for p in body_params if "default" not in p)
            body_args.insert(required_count, "organization_id=self._org_id")
        joined_body = ",\n".join(f"            {arg}" for arg in body_args)
        lines.append(f"        body = {body_type}(\n{joined_body},\n        )\n")

    if refetch:
        refetch_args = ", ".join(param["name"] for param in path_params)
        lines.append(_request_call("response = ", "request_raw"))
        lines.append(
            "        data = response.json()\n"
            '        version_id = data.get("id") if isinstance(data, dict) else None\n'
            "        if version_id is None:\n"
            "            raise RoeAPIException(\n"
            '                f"Unexpected response from server: status={response.status_code}"\n'
            "            )\n"
            "        # POST returns a partial create payload; re-fetch to get the full version.\n"
            f"        return self.retrieve({refetch_args}, str(version_id))\n"
        )
    elif body_type:
        if return_type is None:
            lines.append(_request_call("", "request_json"))
        else:
            lines.append(_request_call("resp = ", "request_json"))
            if empty_message:
                lines.append(
                    "        if resp.parsed is None:\n"
                    f'            raise RoeAPIException("{empty_message}")\n'
                    "        return resp.parsed\n"
                )
            elif return_type == "Any":
                lines.append("        return resp.parsed\n")
            else:
                lines.append(
                    "        return resp.parsed  # type: ignore[return-value]\n"
                )
    elif return_shape == "list":
        label = operation["list_error_label"]
        lines.append(_request_call("response = ", "request_raw"))
        lines.append(
            "        data = response.json()\n"
            "        if not isinstance(data, list):\n"
            "            raise RoeAPIException(\n"
            f'                f"{label} returned unexpected response shape: {{data!r}}"\n'
            "            )\n"
            f"        return [{return_type}.from_dict(item) for item in data]\n"
        )
    elif return_type is not None:
        lines.append(_request_call("response = ", "request_raw"))
        lines.append(f"        return {return_type}.from_dict(response.json())\n")
    else:
        lines.append(_request_call("", "request_raw"))

    return "".join(lines)


def _render_namespace_class(
    api_name: str, parent_class: str, ns_spec: dict[str, Any], suffix: str
) -> str:
    """Render a nested namespace class proxying ``_raw``/``_org_id`` to its parent."""
    class_name = ns_spec["class_name"] + suffix
    parent_arg = f"{api_name}_api"
    methods = [
        _body_kind_method(op) for op in _operations(ns_spec) if op.get("kind") == "body"
    ]

    lines = [f"class {class_name}:\n"]
    if ns_spec.get("docstring"):
        lines.append(_docstring_block(ns_spec["docstring"], "    "))
    lines.append("\n")
    lines.append(f'    def __init__(self, {parent_arg}: "{parent_class}"):\n')
    lines.append(f"        self._{parent_arg} = {parent_arg}\n")
    lines.append("\n")
    lines.append("    @property\n")
    lines.append("    def _raw(self) -> AuthenticatedClient:\n")
    lines.append(f"        return self._{parent_arg}._raw\n")
    lines.append("\n")
    lines.append("    @property\n")
    lines.append("    def _org_id(self) -> UUID:\n")
    lines.append(
        f"        return UUID(str(self._{parent_arg}.config.organization_id))\n"
    )
    lines.append("\n")
    lines.append("\n".join(methods))
    return "".join(lines)


def _render_module(api_name: str, spec: dict[str, Any], *, split: bool) -> str:
    """Render one API module.

    ``split=False`` emits the whole-file facade (today's discovery/tables
    behavior). ``split=True`` emits base classes (``*Generated`` suffix) for
    APIs that also have hand-written ``manual`` operations; the hand-written
    facade later subclasses them.
    """
    suffix = GENERATED_CLASS_SUFFIX if split else ""
    class_name = spec["class_name"] + suffix
    operations = _operations(spec)
    namespaces = _namespaces(spec)
    # Namespaces whose body operations get generated code. A namespace with
    # zero body operations is fully hand-written: no class, no construction.
    generated_namespaces = {
        ns_name: ns_spec
        for ns_name, ns_spec in namespaces.items()
        if _body_kind_ops(ns_spec)
    }

    endpoint_imports: dict[str, list[str]] = defaultdict(list)
    model_imports: dict[str, list[str]] = defaultdict(list)
    needs_unset = False
    needs_roe_api_exception = False
    needs_translate_response = False
    needs_table_upload_helpers = False
    needs_any = False
    needs_uuid = False
    request_helpers: set[str] = set()

    def _scan_body_operation(operation: dict[str, Any]) -> None:
        nonlocal needs_unset, needs_roe_api_exception, needs_any, needs_uuid
        package, endpoint_name = _module_import_parts(operation["endpoint_module"])
        endpoint_imports[package].append(endpoint_name)
        if operation.get("return_import"):
            return_module, return_class = _class_import_parts(
                operation["return_import"]
            )
            model_imports[return_module].append(return_class)
        if operation.get("body_import"):
            body_module, body_class = _class_import_parts(operation["body_import"])
            model_imports[body_module].append(body_class)

        params = operation.get("parameters") or []
        annotations = [param["annotation"] for param in params]
        if operation.get("return_type"):
            annotations.append(operation["return_type"])
        if any(_ANY_RE.search(annotation) for annotation in annotations):
            needs_any = True
        if any(param.get("pass_unset_when_none") for param in params):
            needs_unset = True
        if any(param.get("coerce") == "uuid" for param in params):
            needs_uuid = True
        if (
            operation.get("return_shape") == "list"
            or operation.get("refetch_with_retrieve")
            or (operation.get("body_type") and operation.get("empty_response_message"))
        ):
            needs_roe_api_exception = True
        if operation.get("body_type") and not operation.get("refetch_with_retrieve"):
            request_helpers.add("request_json")
        else:
            request_helpers.add("request_raw")

    methods: list[str] = []
    for operation in operations:
        kind = operation.get("kind", "simple")
        if kind == "simple":
            package, endpoint_name = _module_import_parts(operation["endpoint_module"])
            endpoint_imports[package].append(endpoint_name)
            return_module, return_class = _class_import_parts(
                operation["return_import"]
            )
            model_imports[return_module].append(return_class)
            needs_roe_api_exception = True
            needs_translate_response = True
            if any(
                param.get("pass_unset_when_none")
                for param in operation.get("parameters") or []
            ):
                needs_unset = True
            methods.append(_simple_method(operation))
        elif kind == "table_upload":
            package, endpoint_name = _module_import_parts(operation["endpoint_module"])
            endpoint_imports[package].append(endpoint_name)
            return_module, return_class = _class_import_parts(
                operation["return_import"]
            )
            model_imports[return_module].append(return_class)
            needs_roe_api_exception = True
            needs_translate_response = True
            needs_table_upload_helpers = True
            needs_unset = True
            body_module, body_class = _class_import_parts(operation["body_import"])
            model_imports[body_module].append(body_class)
            methods.append(_table_upload_method(operation))
        elif kind == "body":
            _scan_body_operation(operation)
            methods.append(_body_kind_method(operation))
        elif kind == "manual":
            continue
        else:
            raise ValueError(f"Unsupported wrapper kind {kind!r} in {api_name}")

    api_body_ops = _body_kind_ops(spec)
    if api_body_ops:
        # Every generated body method reads ``self._org_id``.
        needs_uuid = True
    namespace_blocks: list[str] = []
    for ns_name, ns_spec in namespaces.items():
        for operation in _operations(ns_spec):
            ns_kind = operation.get("kind")
            if ns_kind == "body":
                _scan_body_operation(operation)
            elif ns_kind != "manual":
                raise ValueError(
                    f"Unsupported wrapper kind {ns_kind!r} in namespace "
                    f"{api_name}.{ns_name} (only body/manual are allowed)"
                )
        if ns_name in generated_namespaces:
            # Namespace classes proxy ``_org_id`` via the parent config.
            needs_uuid = True
            namespace_blocks.append(
                _render_namespace_class(api_name, class_name, ns_spec, suffix)
            )

    lines = [BASE_HEADER if split else HEADER]
    if needs_table_upload_helpers:
        lines.append("from io import BytesIO\n")
        lines.append("import mimetypes\n")
        lines.append("from pathlib import Path\n")
        lines.append("from typing import BinaryIO\n")
        lines.append("from uuid import UUID\n")
        lines.append("\n")
    else:
        stdlib_lines: list[str] = []
        if needs_any:
            stdlib_lines.append("from typing import Any\n")
        if needs_uuid:
            stdlib_lines.append("from uuid import UUID\n")
        if stdlib_lines:
            lines.extend(stdlib_lines)
            lines.append("\n")

    for package, names in sorted(endpoint_imports.items()):
        unique_names = sorted(set(names))
        if len(unique_names) == 1:
            lines.append(f"from {package} import {unique_names[0]}\n")
        else:
            lines.append(f"from {package} import (\n")
            for name in unique_names:
                lines.append(f"    {name},\n")
            lines.append(")\n")
    lines.append("from roe._generated.client import AuthenticatedClient\n")
    for module, names in sorted(model_imports.items()):
        joined = ", ".join(sorted(set(names)))
        lines.append(f"from {module} import {joined}\n")
    if needs_table_upload_helpers:
        lines.append("from roe._generated.types import File, UNSET, Unset\n")
    elif needs_unset:
        lines.append("from roe._generated.types import UNSET\n")
    lines.append("from roe.config import RoeConfig\n")
    if needs_translate_response and needs_roe_api_exception:
        lines.append("from roe.exceptions import RoeAPIException, translate_response\n")
    elif needs_translate_response:
        lines.append("from roe.exceptions import translate_response\n")
    elif needs_roe_api_exception:
        lines.append("from roe.exceptions import RoeAPIException\n")
    if needs_table_upload_helpers:
        lines.append("from roe.models import FileUpload\n")
    if request_helpers:
        joined_helpers = ", ".join(sorted(request_helpers))
        lines.append(f"from roe.utils.generated_request import {joined_helpers}\n")

    lines.append("\n\n")
    for block in namespace_blocks:
        lines.append(block.rstrip() + "\n")
        lines.append("\n\n")

    lines.append(f"class {class_name}:\n")
    lines.append(_docstring_block(spec.get("docstring", ""), "    "))
    lines.append("\n")
    lines.append(
        "    def __init__(self, config: RoeConfig, raw_client: AuthenticatedClient):\n"
    )
    lines.append("        self.config = config\n")
    lines.append("        self._raw = raw_client\n")
    for ns_name, ns_spec in generated_namespaces.items():
        attr = ns_spec["attr"]
        lines.append(f"        self._{attr} = {ns_spec['class_name']}{suffix}(self)\n")
    lines.append("\n")
    if api_body_ops:
        lines.append("    @property\n")
        lines.append("    def _org_id(self) -> UUID:\n")
        lines.append("        return UUID(str(self.config.organization_id))\n")
        lines.append("\n")
    for ns_name, ns_spec in generated_namespaces.items():
        attr = ns_spec["attr"]
        lines.append("    @property\n")
        lines.append(f"    def {attr}(self) -> {ns_spec['class_name']}{suffix}:\n")
        lines.append(f"        return self._{attr}\n")
        lines.append("\n")
    lines.append("\n".join(methods))

    if needs_table_upload_helpers:
        lines.append(
            "\n\ndef _mime_type(filename: str, override: str | None) -> str:\n"
            "    if override:\n"
            "        return override\n"
            "    guessed, _ = mimetypes.guess_type(filename)\n"
            '    return guessed or "text/csv"\n'
        )

    content = "".join(lines)
    return content.rstrip() + "\n"


def _render_registry(apis: dict[str, dict[str, Any]]) -> str:
    lines = [
        '"""Auto-generated friendly API registry for the Roe SDK."""\n',
        "\n",
        "# Generated by scripts/generate-sdk from openapi/wrappers.yml.\n",
        "# Do not edit by hand.\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
    ]
    if not apis:
        lines.append("\nGENERATED_API_CLASSES: dict[str, type] = {}\n")
        return "".join(lines)
    for api_name, spec in sorted(apis.items()):
        lines.append(f"from roe.api.{api_name} import {spec['class_name']}\n")
    lines.append("\n\n")
    lines.append("GENERATED_API_CLASSES = {\n")
    for api_name, spec in sorted(apis.items()):
        lines.append(f'    "{api_name}": {spec["class_name"]},\n')
    lines.append("}\n")
    return "".join(lines)


def _generate_modules(
    apis: dict[str, dict[str, Any]], api_dir: Path
) -> tuple[dict[str, dict[str, Any]], list[str]]:
    """Write API modules under ``api_dir``.

    Returns ``(whole_file_apis, split_api_names)``. APIs with at least one
    ``manual`` operation (at the API level or inside a namespace) are emitted
    as base-class modules ``_{api}_generated.py``; the rest keep today's
    whole-file behavior and are returned for registry rendering.
    """
    _check_manual_parity(apis, api_dir)
    api_dir.mkdir(parents=True, exist_ok=True)

    whole_file_apis: dict[str, dict[str, Any]] = {}
    split_api_names: list[str] = []
    for api_name, spec in sorted(apis.items()):
        if _spec_has_manual(spec):
            # All-manual APIs (e.g. users) are parity-checked only; emitting an
            # empty base module would add noise without value.
            if _has_generated_ops(spec):
                target = api_dir / f"_{api_name}_generated.py"
                target.write_text(_render_module(api_name, spec, split=True))
                split_api_names.append(api_name)
        else:
            target = api_dir / f"{api_name}.py"
            target.write_text(_render_module(api_name, spec, split=False))
            whole_file_apis[api_name] = spec
    return whole_file_apis, split_api_names


def main() -> None:
    contract = _load_contract()
    apis = contract["apis"]

    whole_file_apis, split_api_names = _generate_modules(apis, API_DIR)
    REGISTRY_PATH.write_text(_render_registry(whole_file_apis))
    _sync_readme_release_banner()
    _sync_readme_block()
    message = (
        f"Generated {len(whole_file_apis)} friendly API wrapper modules from "
        f"{CONTRACT_PATH.relative_to(ROOT_DIR)}"
    )
    if split_api_names:
        message += (
            f" (+{len(split_api_names)} base-class modules: "
            f"{', '.join(split_api_names)})"
        )
    print(message)


if __name__ == "__main__":
    main()
