"""Auto-generated friendly API facades for the Roe SDK."""

# Generated by scripts/generate-sdk from openapi/wrappers.yml.
# Do not edit by hand.

from __future__ import annotations

from typing import Any
from uuid import UUID

from roe._generated.client import AuthenticatedClient
from roe._generated.api.agents import (
    agents_create,
    agents_destroy,
    agents_duplicate_create,
    agents_jobs_cancel_all_create,
    agents_jobs_cancel_create,
    agents_jobs_delete_data_create,
    agents_jobs_result_retrieve,
    agents_jobs_status_retrieve,
    agents_list,
    agents_partial_update,
    agents_retrieve,
    agents_versions_create,
    agents_versions_current_retrieve,
    agents_versions_destroy,
    agents_versions_list,
    agents_versions_partial_update,
    agents_versions_retrieve,
)
from roe._generated.models.agent_job_delete_data_response import (
    AgentJobDeleteDataResponse,
)
from roe._generated.models.agent_job_result_response import AgentJobResultResponse
from roe._generated.models.agent_job_single_status import AgentJobSingleStatus
from roe._generated.models.agent_version import AgentVersion
from roe._generated.models.agent_version_create_request import AgentVersionCreateRequest
from roe._generated.models.base_agent import BaseAgent
from roe._generated.models.base_agent_create_request import BaseAgentCreateRequest
from roe._generated.models.paginated_base_agent_list import PaginatedBaseAgentList
from roe._generated.models.patched_agent_version_update_request import (
    PatchedAgentVersionUpdateRequest,
)
from roe._generated.models.patched_base_agent_update_request import (
    PatchedBaseAgentUpdateRequest,
)
from roe._generated.types import UNSET
from roe.config import RoeConfig
from roe.exceptions import RoeAPIException
from roe.utils.generated_request import request_json, request_raw


class GeneratedAgentVersionsAPI:
    """Nested API for agent version operations.

    Concrete SDK API classes provide ``config`` and ``_raw``."""

    config: RoeConfig
    _raw: AuthenticatedClient

    @property
    def _org_id(self) -> UUID:
        return UUID(str(self.config.organization_id))

    def list(
        self,
        agent_id: str,
    ) -> list[AgentVersion]:
        """"""
        response = request_raw(
            self._raw,
            agents_versions_list,
            UUID(str(agent_id)),
        )
        data = response.json()
        if not isinstance(data, list):
            raise RoeAPIException(
                f"agent versions returned unexpected response shape: {data!r}"
            )
        return [AgentVersion.from_dict(item) for item in data]

    def retrieve(
        self,
        agent_id: str,
        version_id: str,
        get_supports_eval: bool | None = None,
    ) -> AgentVersion:
        """"""
        response = request_raw(
            self._raw,
            agents_versions_retrieve,
            UUID(str(agent_id)),
            UUID(str(version_id)),
            get_supports_eval=get_supports_eval
            if get_supports_eval is not None
            else UNSET,
        )
        return AgentVersion.from_dict(response.json())

    def retrieve_current(
        self,
        agent_id: str,
    ) -> AgentVersion:
        """"""
        response = request_raw(
            self._raw,
            agents_versions_current_retrieve,
            UUID(str(agent_id)),
        )
        return AgentVersion.from_dict(response.json())

    def create(
        self,
        agent_id: str,
        input_definitions: list[dict[str, Any]] | None = None,
        engine_config: dict[str, Any] | None = None,
        version_name: str | None = None,
        description: str | None = None,
    ) -> AgentVersion:
        """"""
        body = AgentVersionCreateRequest(
            input_definitions=input_definitions or [],
            engine_config=engine_config or {},
            version_name=version_name if version_name is not None else UNSET,
            description=description if description is not None else UNSET,
        )
        resp = request_json(
            self._raw,
            agents_versions_create,
            UUID(str(agent_id)),
            body=body,
        )
        created = resp.parsed
        if created is None or created.id is None:
            raise RoeAPIException(
                f"Unexpected response from server: status={resp.status_code}"
            )
        return self.retrieve(agent_id, str(created.id))

    def update(
        self,
        agent_id: str,
        version_id: str,
        version_name: str | None = None,
        description: str | None = None,
    ) -> None:
        """Update an agent version via PATCH (partial update)."""
        body = PatchedAgentVersionUpdateRequest(
            version_name=version_name if version_name is not None else UNSET,
            description=description if description is not None else UNSET,
        )
        request_json(
            self._raw,
            agents_versions_partial_update,
            UUID(str(agent_id)),
            UUID(str(version_id)),
            body=body,
        )
        return None

    def delete(
        self,
        agent_id: str,
        version_id: str,
    ) -> None:
        """"""
        request_raw(
            self._raw,
            agents_versions_destroy,
            UUID(str(agent_id)),
            UUID(str(version_id)),
        )
        return None


class GeneratedAgentJobsAPI:
    """Nested API for agent job operations.

    Concrete SDK API classes provide ``config`` and ``_raw``."""

    config: RoeConfig
    _raw: AuthenticatedClient

    @property
    def _org_id(self) -> UUID:
        return UUID(str(self.config.organization_id))

    def retrieve_status(
        self,
        job_id: str,
    ) -> AgentJobSingleStatus:
        """"""
        response = request_raw(
            self._raw,
            agents_jobs_status_retrieve,
            UUID(str(job_id)),
        )
        return AgentJobSingleStatus.from_dict(response.json())

    def retrieve_result(
        self,
        job_id: str,
    ) -> AgentJobResultResponse:
        """"""
        response = request_raw(
            self._raw,
            agents_jobs_result_retrieve,
            UUID(str(job_id)),
        )
        return AgentJobResultResponse.from_dict(response.json())

    def cancel(
        self,
        job_id: str,
    ) -> None:
        """"""
        request_raw(
            self._raw,
            agents_jobs_cancel_create,
            UUID(str(job_id)),
        )
        return None

    def cancel_all(
        self,
        agent_id: str,
    ) -> None:
        """"""
        request_raw(
            self._raw,
            agents_jobs_cancel_all_create,
            UUID(str(agent_id)),
        )
        return None

    def delete_data(
        self,
        job_id: str,
    ) -> AgentJobDeleteDataResponse:
        """"""
        response = request_raw(
            self._raw,
            agents_jobs_delete_data_create,
            UUID(str(job_id)),
        )
        return AgentJobDeleteDataResponse.from_dict(response.json())


class GeneratedAgentsAPI:
    """API for managing and running agents.

    Concrete SDK API classes provide ``config`` and ``_raw``."""

    config: RoeConfig
    _raw: AuthenticatedClient

    @property
    def _org_id(self) -> UUID:
        return UUID(str(self.config.organization_id))

    def list(
        self,
        page: int | None = None,
        page_size: int | None = None,
    ) -> PaginatedBaseAgentList:
        """"""
        response = request_raw(
            self._raw,
            agents_list,
            page=page if page is not None else UNSET,
            page_size=page_size if page_size is not None else UNSET,
        )
        return PaginatedBaseAgentList.from_dict(response.json())

    def retrieve(
        self,
        agent_id: str,
    ) -> BaseAgent:
        """"""
        response = request_raw(
            self._raw,
            agents_retrieve,
            UUID(str(agent_id)),
        )
        return BaseAgent.from_dict(response.json())

    def create(
        self,
        name: str,
        engine_class_id: str,
        input_definitions: list[dict[str, Any]] | None = None,
        engine_config: dict[str, Any] | None = None,
        version_name: str | None = None,
        description: str | None = None,
    ) -> BaseAgent:
        """"""
        body = BaseAgentCreateRequest(
            organization_id=self._org_id,
            name=name,
            engine_class_id=engine_class_id,
            input_definitions=input_definitions or [],
            engine_config=engine_config or {},
            version_name=version_name if version_name is not None else UNSET,
            description=description if description is not None else UNSET,
        )
        resp = request_json(
            self._raw,
            agents_create,
            body=body,
            organization_id=self._org_id,
        )
        return resp.parsed  # type: ignore[return-value]

    def update(
        self,
        agent_id: str,
        name: str | None = None,
        disable_cache: bool | None = None,
        cache_failed_jobs: bool | None = None,
    ) -> BaseAgent:
        """Update an agent via PATCH (partial update)."""
        body = PatchedBaseAgentUpdateRequest(
            name=name if name is not None else UNSET,
            disable_cache=disable_cache if disable_cache is not None else UNSET,
            cache_failed_jobs=cache_failed_jobs
            if cache_failed_jobs is not None
            else UNSET,
        )
        resp = request_json(
            self._raw,
            agents_partial_update,
            UUID(str(agent_id)),
            body=body,
        )
        return resp.parsed  # type: ignore[return-value]

    def delete(
        self,
        agent_id: str,
    ) -> None:
        """"""
        request_raw(
            self._raw,
            agents_destroy,
            UUID(str(agent_id)),
        )
        return None

    def duplicate(
        self,
        agent_id: str,
    ) -> AgentVersion:
        """Duplicate an agent. Returns the resulting ``AgentVersion``.

        The endpoint historically returned a JSON object with a ``base_agent``
        key wrapping the new agent; the generated client now models the
        response as ``AgentVersion`` directly. Callers wanting the new base
        agent should read ``result.base_agent`` (already populated)."""
        response = request_raw(
            self._raw,
            agents_duplicate_create,
            UUID(str(agent_id)),
        )
        return AgentVersion.from_dict(response.json())
