"""Auto-generated friendly API registry for the Roe AI SDK."""

# Generated by scripts/generate-sdk from openapi/wrappers.yml.
# Do not edit by hand.

from __future__ import annotations

from roe.api.discovery import DiscoveryAPI
from roe.api.tables import TablesAPI


GENERATED_API_CLASSES = {
    "discovery": DiscoveryAPI,
    "tables": TablesAPI,
}
