"""Auto-generated friendly API facades for the Roe SDK."""

# Generated by scripts/generate-sdk from openapi/wrappers.yml.
# Do not edit by hand.

from __future__ import annotations

from typing import Any
from uuid import UUID

from roe._generated.api.policies import (
    policies_create,
    policies_destroy,
    policies_list,
    policies_partial_update,
    policies_retrieve,
)
from roe._generated.models.create_policy import CreatePolicy
from roe._generated.models.create_policy_request import CreatePolicyRequest
from roe._generated.models.paginated_policy_list import PaginatedPolicyList
from roe._generated.models.patched_update_policy_request import (
    PatchedUpdatePolicyRequest,
)
from roe._generated.models.policy import Policy
from roe._generated.types import UNSET
from roe.utils.generated_request import request_json, request_raw


class GeneratedPoliciesAPI:
    """API for managing policies used by agentic workflows."""

    @property
    def _org_id(self) -> UUID:
        return UUID(str(self.config.organization_id))

    def list(
        self,
        page: int | None = None,
        page_size: int | None = None,
    ) -> PaginatedPolicyList:
        """List policies in the organization."""
        response = request_raw(
            self._raw,
            policies_list,
            page=page if page is not None else UNSET,
            page_size=page_size if page_size is not None else UNSET,
        )
        return PaginatedPolicyList.from_dict(response.json())

    def retrieve(
        self,
        policy_id: str,
    ) -> Policy:
        """Retrieve a specific policy by ID."""
        response = request_raw(
            self._raw,
            policies_retrieve,
            UUID(str(policy_id)),
        )
        return Policy.from_dict(response.json())

    def create(
        self,
        name: str,
        content: dict[str, Any],
        description: str = "",
        version_name: str | None = None,
    ) -> CreatePolicy:
        """Create a new policy with an initial version."""
        body = CreatePolicyRequest(
            name=name,
            content=content,
            description=description,
            version_name=version_name if version_name is not None else UNSET,
        )
        resp = request_json(
            self._raw,
            policies_create,
            body=body,
        )
        return resp.parsed  # type: ignore[return-value]

    def update(
        self,
        policy_id: str,
        name: str | None = None,
        description: str | None = None,
    ) -> Any:
        """Update a policy's metadata via PATCH (partial update)."""
        body = PatchedUpdatePolicyRequest(
            name=name if name is not None else UNSET,
            description=description if description is not None else UNSET,
        )
        resp = request_json(
            self._raw,
            policies_partial_update,
            UUID(str(policy_id)),
            body=body,
        )
        return resp.parsed  # type: ignore[return-value]

    def delete(
        self,
        policy_id: str,
    ) -> None:
        """Delete a policy and all its versions."""
        request_raw(
            self._raw,
            policies_destroy,
            UUID(str(policy_id)),
        )
        return None
