"""Auto-generated friendly API facades for the Roe SDK."""

# Generated by scripts/generate-sdk from openapi/wrappers.yml.
# Do not edit by hand.

from __future__ import annotations

from roe._generated.api.connectors import (
    connectors_retrieve,
    connectors_retrieve_by_type,
)
from roe._generated.client import AuthenticatedClient
from roe._generated.models.connector_list_response import ConnectorListResponse
from roe._generated.models.connector_metadata import ConnectorMetadata
from roe.config import RoeConfig
from roe.utils.generated_request import request_raw


class ConnectorsAPI:
    """API for discovering available connector types."""

    def __init__(self, config: RoeConfig, raw_client: AuthenticatedClient):
        self.config = config
        self._raw = raw_client

    def list(self) -> ConnectorListResponse:
        """List available connector types."""
        response = request_raw(
            self._raw,
            connectors_retrieve,
        )
        return ConnectorListResponse.from_dict(response.json())

    def retrieve(
        self,
        connector_type: str,
    ) -> ConnectorMetadata:
        """Retrieve metadata for a connector type."""
        response = request_raw(
            self._raw,
            connectors_retrieve_by_type,
            connector_type,
        )
        return ConnectorMetadata.from_dict(response.json())
