"""Auto-generated friendly API facades for the Roe SDK."""

# Generated by scripts/generate-sdk from openapi/wrappers.yml.
# Do not edit by hand.

from __future__ import annotations

from typing import Any
from uuid import UUID

from roe._generated.api.connections import (
    connections_create,
    connections_destroy,
    connections_list,
    connections_partial_update,
    connections_retrieve,
    connections_test_create,
    connections_test_credentials_create,
    connections_update,
)
from roe._generated.client import AuthenticatedClient
from roe._generated.models.connection import Connection
from roe._generated.models.paginated_connection_list_list import (
    PaginatedConnectionListList,
)
from roe._generated.models.test_connection import TestConnection
from roe._generated.types import UNSET
from roe.config import RoeConfig
from roe.utils.generated_request import request_json, request_raw


class ConnectionsAPI:
    """API for managing external data connections."""

    def __init__(self, config: RoeConfig, raw_client: AuthenticatedClient):
        self.config = config
        self._raw = raw_client

    @property
    def _org_id(self) -> UUID:
        return UUID(str(self.config.organization_id))

    def list(
        self,
        connector_type: str | None = None,
        search: str | None = None,
        page: int | None = None,
        page_size: int | None = None,
    ) -> PaginatedConnectionListList:
        """List connections."""
        response = request_raw(
            self._raw,
            connections_list,
            connector_type=connector_type if connector_type is not None else UNSET,
            search=search if search is not None else UNSET,
            page=page if page is not None else UNSET,
            page_size=page_size if page_size is not None else UNSET,
            organization_id=self._org_id,
        )
        return PaginatedConnectionListList.from_dict(response.json())

    def create(
        self,
        connector_type: str,
        name: str,
        config: dict[str, Any],
        description: str | None = None,
        auth_config: dict[str, Any] | None = None,
    ) -> Connection:
        """Create a connection."""
        body: dict[str, Any] = {}
        body["organization_id"] = str(self._org_id)
        body["connector_type"] = connector_type
        body["name"] = name
        body["config"] = config
        if description is not None:
            body["description"] = description
        if auth_config is not None:
            body["auth_config"] = auth_config
        resp = request_json(
            self._raw,
            connections_create,
            body=body,
            organization_id=self._org_id,
        )
        return resp.parsed  # type: ignore[return-value]

    def test_credentials(
        self,
        connector_type: str,
        config: dict[str, Any],
        auth_config: dict[str, Any] | None = None,
    ) -> TestConnection:
        """Test connection credentials without saving a connection."""
        body: dict[str, Any] = {}
        body["connector_type"] = connector_type
        body["config"] = config
        if auth_config is not None:
            body["auth_config"] = auth_config
        resp = request_json(
            self._raw,
            connections_test_credentials_create,
            body=body,
        )
        return resp.parsed  # type: ignore[return-value]

    def retrieve(
        self,
        connection_id: str,
    ) -> Connection:
        """Retrieve a connection."""
        response = request_raw(
            self._raw,
            connections_retrieve,
            connection_id,
            organization_id=self._org_id,
        )
        return Connection.from_dict(response.json())

    def update(
        self,
        connection_id: str,
        name: str | None = None,
        description: str | None = None,
        config: dict[str, Any] | None = None,
        auth_config: dict[str, Any] | None = None,
    ) -> Connection:
        """Update mutable connection fields."""
        body: dict[str, Any] = {}
        body["organization_id"] = str(self._org_id)
        if name is not None:
            body["name"] = name
        if description is not None:
            body["description"] = description
        if config is not None:
            body["config"] = config
        if auth_config is not None:
            body["auth_config"] = auth_config
        resp = request_json(
            self._raw,
            connections_partial_update,
            connection_id,
            body=body,
            organization_id=self._org_id,
        )
        return resp.parsed  # type: ignore[return-value]

    def replace(
        self,
        connection_id: str,
        name: str | None = None,
        description: str | None = None,
        config: dict[str, Any] | None = None,
        auth_config: dict[str, Any] | None = None,
    ) -> Connection:
        """Replace a connection."""
        body: dict[str, Any] = {}
        body["organization_id"] = str(self._org_id)
        if name is not None:
            body["name"] = name
        if description is not None:
            body["description"] = description
        if config is not None:
            body["config"] = config
        if auth_config is not None:
            body["auth_config"] = auth_config
        resp = request_json(
            self._raw,
            connections_update,
            connection_id,
            body=body,
            organization_id=self._org_id,
        )
        return resp.parsed  # type: ignore[return-value]

    def delete(
        self,
        connection_id: str,
    ) -> None:
        """Delete a connection."""
        request_raw(
            self._raw,
            connections_destroy,
            connection_id,
            organization_id=self._org_id,
        )
        return None

    def test(
        self,
        connection_id: str,
    ) -> TestConnection:
        """Test a saved connection."""
        response = request_raw(
            self._raw,
            connections_test_create,
            connection_id,
            organization_id=self._org_id,
        )
        return TestConnection.from_dict(response.json())
