"""Auto-generated friendly API facades for the Roe SDK."""

# Generated by scripts/generate-sdk from openapi/wrappers.yml.
# Do not edit by hand.

from __future__ import annotations

from roe._generated.api.discovery import (
    discovery_agent_engine_types_list,
    discovery_supported_models_list,
)
from roe._generated.client import AuthenticatedClient
from roe._generated.models.agent_engine_type_list import AgentEngineTypeList
from roe._generated.models.supported_llm_model_list import SupportedLLMModelList
from roe._generated.types import UNSET
from roe.config import RoeConfig
from roe.exceptions import RoeAPIException, translate_response


class DiscoveryAPI:
    """API for discovering valid agent engine types and model IDs."""

    def __init__(self, config: RoeConfig, raw_client: AuthenticatedClient):
        self.config = config
        self._raw = raw_client

    def list_agent_engine_types(self) -> AgentEngineTypeList:
        """Return production engine_class_id values accepted by agent creation."""
        response = discovery_agent_engine_types_list.sync_detailed(
            client=self._raw,
        )
        translate_response(response)
        if response.parsed is None:
            raise RoeAPIException("agent engine discovery returned an empty response")
        return response.parsed

    def list_supported_models(
        self,
        capability: str | None = None,
    ) -> SupportedLLMModelList:
        """Return non-deprecated model IDs accepted in engine_config.model."""
        response = discovery_supported_models_list.sync_detailed(
            client=self._raw,
            capability=capability if capability is not None else UNSET,
        )
        translate_response(response)
        if response.parsed is None:
            raise RoeAPIException("model discovery returned an empty response")
        return response.parsed
