"""Auto-generated friendly API facades for the Roe SDK."""

# Generated by scripts/generate-sdk from openapi/wrappers.yml.
# Do not edit by hand.

from __future__ import annotations

from typing import Any

from roe._generated.api.sdk import (
    skill_sets_create,
    skill_sets_destroy,
    skill_sets_generate_version,
    skill_sets_generation_cancel,
    skill_sets_generation_retrieve,
    skill_sets_list,
    skill_sets_partial_update,
    skill_sets_retrieve,
    skill_sets_set_current_version,
    skill_sets_versions_create,
    skill_sets_versions_list,
    skill_sets_versions_retrieve,
)
from roe._generated.client import AuthenticatedClient
from roe._generated.models.create_skill_set import CreateSkillSet
from roe._generated.models.create_skill_set_version import CreateSkillSetVersion
from roe._generated.models.generate_skill_set_version_response import (
    GenerateSkillSetVersionResponse,
)
from roe._generated.models.paginated_skill_set_list import PaginatedSkillSetList
from roe._generated.models.paginated_skill_set_version_list import (
    PaginatedSkillSetVersionList,
)
from roe._generated.models.public_skill_set_generation import PublicSkillSetGeneration
from roe._generated.models.skill_set import SkillSet
from roe._generated.models.skill_set_version import SkillSetVersion
from roe._generated.models.update_skill_set import UpdateSkillSet
from roe._generated.types import UNSET
from roe.config import RoeConfig
from roe.utils.generated_request import request_json, request_raw


class SkillSetsAPI:
    """Manage skill sets, immutable versions, and generation."""

    def __init__(self, config: RoeConfig, raw_client: AuthenticatedClient):
        self.config = config
        self._raw = raw_client

    def list(
        self,
        ordering: str | None = None,
        page: int | None = None,
        page_size: int | None = None,
        search: str | None = None,
        organization_id: str | None = None,
    ) -> PaginatedSkillSetList:
        """List skill sets."""
        response = request_raw(
            self._raw,
            skill_sets_list,
            ordering=ordering if ordering is not None else UNSET,
            page=page if page is not None else UNSET,
            page_size=page_size if page_size is not None else UNSET,
            search=search if search is not None else UNSET,
            organization_id=organization_id if organization_id is not None else UNSET,
        )
        return PaginatedSkillSetList.from_dict(response.json())

    def create(
        self,
        name: str,
        organization_id: str | None = None,
        description: str | None = None,
    ) -> CreateSkillSet:
        """Create a skill set with its initial base version."""
        body: dict[str, Any] = {}
        body["name"] = name
        if description is not None:
            body["description"] = description
        resp = request_json(
            self._raw,
            skill_sets_create,
            body=body,
            organization_id=organization_id if organization_id is not None else UNSET,
        )
        return resp.parsed  # type: ignore[return-value]

    def retrieve(
        self,
        id: str,
        organization_id: str | None = None,
    ) -> SkillSet:
        """Retrieve skill-set metadata."""
        response = request_raw(
            self._raw,
            skill_sets_retrieve,
            id,
            organization_id=organization_id if organization_id is not None else UNSET,
        )
        return SkillSet.from_dict(response.json())

    def update(
        self,
        id: str,
        organization_id: str | None = None,
        name: str | None = None,
        description: str | None = None,
    ) -> UpdateSkillSet:
        """Update skill-set metadata."""
        body: dict[str, Any] = {}
        if name is not None:
            body["name"] = name
        if description is not None:
            body["description"] = description
        resp = request_json(
            self._raw,
            skill_sets_partial_update,
            id,
            body=body,
            organization_id=organization_id if organization_id is not None else UNSET,
        )
        return resp.parsed  # type: ignore[return-value]

    def delete(
        self,
        id: str,
        organization_id: str | None = None,
    ) -> None:
        """Delete a skill set and its versions unless referenced by agents."""
        request_raw(
            self._raw,
            skill_sets_destroy,
            id,
            organization_id=organization_id if organization_id is not None else UNSET,
        )
        return None

    def generate_version(
        self,
        skill_set_id: str,
        use_case: str,
        organization_id: str | None = None,
        base_version_id: str | None = None,
        auto_commit: bool | None = None,
        table_names: list[str] | None = None,
        attachments: list[str] | None = None,
        policy_id: str | None = None,
        policy_version_id: str | None = None,
    ) -> GenerateSkillSetVersionResponse:
        """Start asynchronous generation. Pass empty slices for unused tables and attachments."""
        body: dict[str, Any] = {}
        body["use_case"] = use_case
        if base_version_id is not None:
            body["base_version_id"] = base_version_id
        if auto_commit is not None:
            body["auto_commit"] = auto_commit
        if table_names is not None:
            body["table_names"] = table_names
        if attachments is not None:
            body["attachments"] = attachments
        if policy_id is not None:
            body["policy_id"] = policy_id
        if policy_version_id is not None:
            body["policy_version_id"] = policy_version_id
        resp = request_json(
            self._raw,
            skill_sets_generate_version,
            skill_set_id,
            body=body,
            organization_id=organization_id if organization_id is not None else UNSET,
        )
        return resp.parsed  # type: ignore[return-value]

    def get_generation(
        self,
        skill_set_id: str,
        organization_id: str | None = None,
    ) -> PublicSkillSetGeneration:
        """Read the tracked generation, or null when none exists."""
        response = request_raw(
            self._raw,
            skill_sets_generation_retrieve,
            skill_set_id,
            organization_id=organization_id if organization_id is not None else UNSET,
        )
        return PublicSkillSetGeneration.from_dict(response.json())

    def cancel_generation(
        self,
        run_id: str,
        skill_set_id: str,
        organization_id: str | None = None,
    ) -> None:
        """Cancel and stop tracking a generation."""
        request_raw(
            self._raw,
            skill_sets_generation_cancel,
            run_id,
            skill_set_id,
            organization_id=organization_id if organization_id is not None else UNSET,
        )
        return None

    def set_current_version(
        self,
        skill_set_id: str,
        version_id: str,
        organization_id: str | None = None,
    ) -> SkillSet:
        """Select the current version of a skill set."""
        response = request_raw(
            self._raw,
            skill_sets_set_current_version,
            skill_set_id,
            version_id,
            organization_id=organization_id if organization_id is not None else UNSET,
        )
        return SkillSet.from_dict(response.json())

    def list_versions(
        self,
        skill_set_id: str,
        page: int | None = None,
        page_size: int | None = None,
        organization_id: str | None = None,
    ) -> PaginatedSkillSetVersionList:
        """List versions of a skill set."""
        response = request_raw(
            self._raw,
            skill_sets_versions_list,
            skill_set_id,
            page=page if page is not None else UNSET,
            page_size=page_size if page_size is not None else UNSET,
            organization_id=organization_id if organization_id is not None else UNSET,
        )
        return PaginatedSkillSetVersionList.from_dict(response.json())

    def create_version(
        self,
        skill_set_id: str,
        files: list[dict[str, Any]],
        organization_id: str | None = None,
        version_name: str | None = None,
        base_version_id: str | None = None,
        summary: str | None = None,
        file_changes: list[dict[str, Any]] | None = None,
    ) -> CreateSkillSetVersion:
        """Create a complete version and make it current."""
        body: dict[str, Any] = {}
        body["files"] = files
        if version_name is not None:
            body["version_name"] = version_name
        if base_version_id is not None:
            body["base_version_id"] = base_version_id
        if summary is not None:
            body["summary"] = summary
        if file_changes is not None:
            body["file_changes"] = file_changes
        resp = request_json(
            self._raw,
            skill_sets_versions_create,
            skill_set_id,
            body=body,
            organization_id=organization_id if organization_id is not None else UNSET,
        )
        return resp.parsed  # type: ignore[return-value]

    def retrieve_version(
        self,
        id: str,
        organization_id: str | None = None,
    ) -> SkillSetVersion:
        """Read a version and its complete file collection."""
        response = request_raw(
            self._raw,
            skill_sets_versions_retrieve,
            id,
            organization_id=organization_id if organization_id is not None else UNSET,
        )
        return SkillSetVersion.from_dict(response.json())
