"""Auto-generated friendly API facades for the Roe SDK."""

# Generated by scripts/generate-sdk from openapi/wrappers.yml.
# Do not edit by hand.

from __future__ import annotations

from io import BytesIO
import mimetypes
from pathlib import Path
from typing import BinaryIO
from uuid import UUID

from roe._generated.api.tables import (
    tables_describe_retrieve,
    tables_destroy,
    tables_list,
    tables_preview_retrieve,
    tables_query_create,
    tables_query_result_retrieve,
    upload_table,
)
from roe._generated.client import AuthenticatedClient
from roe._generated.models.table_describe_response import TableDescribeResponse
from roe._generated.models.table_list_response import TableListResponse
from roe._generated.models.table_preview_response import TablePreviewResponse
from roe._generated.models.table_query_request import TableQueryRequest
from roe._generated.models.table_query_result_response import TableQueryResultResponse
from roe._generated.models.table_query_submit_response import TableQuerySubmitResponse
from roe._generated.models.table_upload_request import TableUploadRequest
from roe._generated.models.table_upload_response import TableUploadResponse
from roe._generated.types import File, UNSET, Unset
from roe.config import RoeConfig
from roe.exceptions import RoeAPIException, translate_response
from roe.models import FileUpload
from roe.utils.generated_request import request_json, request_raw


class TablesAPI:
    """API for managing Roe tables."""

    def __init__(self, config: RoeConfig, raw_client: AuthenticatedClient):
        self.config = config
        self._raw = raw_client

    def list(self) -> TableListResponse:
        """List Roe tables."""
        response = request_raw(
            self._raw,
            tables_list,
        )
        return TableListResponse.from_dict(response.json())

    def upload(
        self,
        *,
        table_name: str,
        file: str | Path | bytes | BinaryIO | FileUpload,
        with_headers: bool = True,
        organization_id: str | UUID | None = None,
        filename: str | None = None,
        mime_type: str | None = None,
    ) -> TableUploadResponse:
        """Upload a CSV file and create a Roe table.

        Args:
            table_name: Name of the table to create.
            file: CSV file path, bytes, binary file object, or ``FileUpload``.
            with_headers: Whether the first CSV row contains column headers.
            organization_id: Optional override; defaults to the client's configured org.
            filename: Filename to use for bytes/file objects.
            mime_type: MIME type override. Defaults to ``text/csv`` for ``.csv`` names.
        """
        resolved_org: UUID | Unset
        candidate = organization_id or self.config.organization_id
        resolved_org = UUID(str(candidate)) if candidate else UNSET

        upload_file, close_after = self._as_generated_file(file, filename, mime_type)
        try:
            body = TableUploadRequest(
                table_name=table_name,
                file=upload_file,
                with_headers=with_headers,
                organization_id=resolved_org,
            )
            response = upload_table.sync_detailed(client=self._raw, body=body)
            translate_response(response)
            if not isinstance(response.parsed, TableUploadResponse):
                raise RoeAPIException("table upload returned an empty response")
            return response.parsed
        finally:
            if close_after:
                upload_file.payload.close()

    @staticmethod
    def _as_generated_file(
        file: str | Path | bytes | BinaryIO | FileUpload,
        filename: str | None,
        mime_type: str | None,
    ) -> tuple[File, bool]:
        if isinstance(file, FileUpload):
            payload = file.open()
            effective_filename = filename or file.effective_filename
            effective_mime_type = mime_type or file.effective_mime_type
            return (
                File(
                    payload=payload,
                    file_name=effective_filename,
                    mime_type=effective_mime_type,
                ),
                file.path is not None,
            )

        if isinstance(file, (str, Path)):
            path = Path(file)
            payload = path.open("rb")
            effective_filename = filename or path.name
            return (
                File(
                    payload=payload,
                    file_name=effective_filename,
                    mime_type=_mime_type(effective_filename, mime_type),
                ),
                True,
            )

        if isinstance(file, bytes):
            effective_filename = filename or "upload.csv"
            return (
                File(
                    payload=BytesIO(file),
                    file_name=effective_filename,
                    mime_type=_mime_type(effective_filename, mime_type),
                ),
                True,
            )

        effective_filename = filename or Path(getattr(file, "name", "upload.csv")).name
        return (
            File(
                payload=file,
                file_name=effective_filename,
                mime_type=_mime_type(effective_filename, mime_type),
            ),
            False,
        )

    def query(
        self,
        sql: str,
        limit: int | None = None,
    ) -> TableQuerySubmitResponse:
        """Run a read-only query against Roe tables."""
        body = TableQueryRequest(
            sql=sql,
            limit=limit if limit is not None else UNSET,
        )
        resp = request_json(
            self._raw,
            tables_query_create,
            body=body,
        )
        return resp.parsed  # type: ignore[return-value]

    def query_result(
        self,
        table_query_id: str,
    ) -> TableQueryResultResponse:
        """Get the result for a submitted table query."""
        response = request_raw(
            self._raw,
            tables_query_result_retrieve,
            table_query_id,
        )
        return TableQueryResultResponse.from_dict(response.json())

    def describe(
        self,
        table_name: str,
    ) -> TableDescribeResponse:
        """Describe a Roe table."""
        response = request_raw(
            self._raw,
            tables_describe_retrieve,
            table_name,
        )
        return TableDescribeResponse.from_dict(response.json())

    def preview(
        self,
        table_name: str,
        limit: int | None = None,
    ) -> TablePreviewResponse:
        """Preview rows from a Roe table."""
        response = request_raw(
            self._raw,
            tables_preview_retrieve,
            table_name,
            limit=limit if limit is not None else UNSET,
        )
        return TablePreviewResponse.from_dict(response.json())

    def delete(
        self,
        table_name: str,
    ) -> None:
        """Delete a Roe table."""
        request_raw(
            self._raw,
            tables_destroy,
            table_name,
        )
        return None


def _mime_type(filename: str, override: str | None) -> str:
    if override:
        return override
    guessed, _ = mimetypes.guess_type(filename)
    return guessed or "text/csv"
